global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 3
  download_limit: 1
  last_check_time: '2025-12-16 03:14:48'
- name: 电锯人
  path: dianjuren
  last_chapter: 3
  download_limit: 1
  last_check_time: '2025-12-16 03:15:07'
